# Generated by Django 3.2.7 on 2022-10-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.EmailField(max_length=1000000)),
                ('teu', models.CharField(default='1', max_length=1000000)),
            ],
        ),
    ]
