# Generated by Django 3.2.7 on 2022-10-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='carbon',
            field=models.EmailField(default=1, max_length=1000000),
            preserve_default=False,
        ),
    ]
